platform :ios, '10.0'

target 'Analytics-iAds-Attribution_Example' do
  pod 'Analytics-iAds-Attribution', :path => '../'
  pod 'Analytics'

  target 'Analytics-iAds-Attribution_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
  end
end
